CREATE TABLE COMPANY(
   ID INT PRIMARY KEY NOT NULL,
   NAME TEXT NOT NULL,
   AGE INT NOT NULL,
   ADDRESS CHAR(50),
   SALARY REAL
);

CREATE TABLE AUDIT(
   EMP_ID INT NOT NULL,
   ENTRY_DATE TEXT NOT NULL
);

CREATE OR REPLACE FUNCTION auditlog() RETURNS TRIGGER AS $$
BEGIN
   INSERT INTO AUDIT(EMP_ID, ENTRY_DATE) VALUES (NEW.ID, current_timestamp);
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER example_trigger 
AFTER INSERT ON COMPANY
FOR EACH ROW 
EXECUTE FUNCTION auditlog();

INSERT INTO COMPANY (ID, NAME, AGE, ADDRESS, SALARY)
VALUES (1, 'Raju', 25, 'New-Delhi', 33000.00 );

SELECT * FROM COMPANY;
SELECT * FROM AUDIT;

